import type { Asset, Owner } from '../types/domain';

export const MOCK_USER: Owner = {
  name: '김상우',
  email: 'sangwoo.kim@lge.com',
  dept: '보안솔루션실',
};

export const OS_OPTIONS = [
  'Windows 11',
  'Windows 10',
  'Windows Server 2022',
  'Windows Server 2019',
  'macOS Sonoma',
  'macOS Ventura',
  'Ubuntu 22.04',
  'Ubuntu 20.04',
  'RHEL 9',
  'RHEL 8',
  'CentOS 7',
  '기타',
];

export const LOCATION_OPTIONS = [
  '서울 마곡 LG사이언스파크',
  '서울 여의도 LG트윈타워',
  '평택 디지털파크',
  '구미 사업장',
  '창원 사업장',
  '대전 R&D센터',
  '기타',
];

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'ASSET-008291',
    hostname: 'dev-server-01',
    domain: 'lge.com',
    ips: ['10.20.30.40'],
    os: 'Ubuntu 22.04',
    osVersion: '22.04.3 LTS',
    location: '서울 마곡 LG사이언스파크',
    internet: 'no',
    antivirus: 'installed',
    edr: 'installed',
    owner: null,
    qualysDetectedAt: '2026-04-12T09:33:00Z',
    updatedAt: null,
    updatedBy: null,
  },
  {
    id: 'ASSET-008292',
    hostname: 'dev-db-primary',
    domain: 'lge.com',
    ips: ['10.20.30.42', '10.20.30.43'],
    os: 'RHEL 9',
    osVersion: '9.2',
    location: '서울 마곡 LG사이언스파크',
    internet: 'no',
    antivirus: 'installed',
    edr: 'installed',
    owner: { name: '박지훈', email: 'jihoon.park@lge.com', dept: '보안운영실' },
    qualysDetectedAt: '2026-04-10T12:18:00Z',
    updatedAt: '2026-05-20T13:11:00Z',
    updatedBy: '박지훈',
  },
  {
    id: 'ASSET-008301',
    hostname: 'app-stage-04',
    domain: 'lge.com',
    ips: ['10.42.5.18'],
    os: 'Ubuntu 20.04',
    osVersion: '20.04.6',
    location: '평택 디지털파크',
    internet: 'yes',
    antivirus: 'installed',
    edr: 'not-installed',
    owner: { name: '정유진', email: 'yujin.jung@lge.com', dept: '클라우드플랫폼팀' },
    qualysDetectedAt: '2026-04-08T15:01:00Z',
    updatedAt: '2026-05-21T11:47:00Z',
    updatedBy: '정유진',
  },
  {
    id: 'ASSET-008312',
    hostname: 'jenkins-master',
    domain: 'lge.com',
    ips: ['172.16.8.91'],
    os: 'Ubuntu 22.04',
    osVersion: '22.04.4',
    location: '서울 마곡 LG사이언스파크',
    internet: 'no',
    antivirus: 'installed',
    edr: 'installed',
    owner: null,
    qualysDetectedAt: '2026-04-15T08:22:00Z',
    updatedAt: null,
    updatedBy: null,
  },
  {
    id: 'ASSET-008325',
    hostname: 'rd-bench-22',
    domain: 'lge.com',
    ips: ['10.55.12.7'],
    os: 'Windows 11',
    osVersion: '23H2',
    location: '대전 R&D센터',
    internet: 'yes',
    antivirus: 'installed',
    edr: 'installed',
    owner: { name: '이수민', email: 'sumin.lee@lge.com', dept: '단말연구소' },
    qualysDetectedAt: '2026-04-11T10:05:00Z',
    updatedAt: '2026-05-19T15:34:00Z',
    updatedBy: '이수민',
  },
  {
    id: 'ASSET-008341',
    hostname: 'qa-runner-01',
    domain: 'lge.com',
    ips: ['10.88.4.130'],
    os: 'Windows Server 2022',
    osVersion: '21H2',
    location: '구미 사업장',
    internet: 'no',
    antivirus: 'installed',
    edr: 'installed',
    owner: null,
    qualysDetectedAt: '2026-04-09T11:48:00Z',
    updatedAt: null,
    updatedBy: null,
  },
  {
    id: 'ASSET-008412',
    hostname: 'mac-jhpark',
    domain: 'lge.com',
    ips: ['10.20.40.18'],
    os: 'macOS Sonoma',
    osVersion: '14.4.1',
    location: '서울 여의도 LG트윈타워',
    internet: 'yes',
    antivirus: 'installed',
    edr: 'installed',
    owner: { name: '박지훈', email: 'jihoon.park@lge.com', dept: '보안운영실' },
    qualysDetectedAt: '2026-04-05T09:00:00Z',
    updatedAt: '2026-05-18T17:02:00Z',
    updatedBy: '박지훈',
  },
  {
    id: 'ASSET-008498',
    hostname: 'test-bench-08',
    domain: 'lge.com',
    ips: ['10.20.30.55'],
    os: 'Ubuntu 20.04',
    osVersion: '20.04.5',
    location: '평택 디지털파크',
    internet: 'no',
    antivirus: 'not-installed',
    edr: 'not-installed',
    owner: null,
    qualysDetectedAt: '2026-04-13T14:22:00Z',
    updatedAt: null,
    updatedBy: null,
  },
];
